# -*- coding: utf-8 -*-
"""huyen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iptv9sqG19zoq_5iYB3kr-1EcBe9TFIc
"""

# CELL 1: CÀI ĐẶT CƠ BẢN
!pip install opencv-python numpy matplotlib -q

import cv2
import numpy as np
import os
import json
from datetime import datetime

# Tạo thư mục output
os.makedirs('/kaggle/working/output/layers', exist_ok=True)

!wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth

# CELL 2: CLASS CHÍNH
class SimpleLayerExtractor:
    def __init__(self):
        print("🎨 Khởi tạo Simple Layer Extractor")

    def create_sample_image(self):
        """Tạo ảnh mẫu với các vật thể"""
        img = np.ones((512, 768, 3), dtype=np.uint8) * 240

        # Background (toàn bộ)
        cv2.rectangle(img, (0, 0), (768, 512), (200, 220, 240), -1)

        # Book - hình chữ nhật
        cv2.rectangle(img, (100, 150), (400, 400), (180, 120, 80), -1)
        cv2.putText(img, 'BOOK', (180, 280), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2)

        # Pen - hình trụ
        cv2.rectangle(img, (450, 200), (500, 350), (60, 60, 180), -1)
        cv2.circle(img, (475, 200), 25, (60, 60, 180), -1)
        cv2.putText(img, 'PEN', (455, 300), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,255,255), 2)

        # Notebook - hình chữ nhật
        cv2.rectangle(img, (550, 100), (700, 250), (80, 160, 80), -1)
        cv2.putText(img, 'NOTEBOOK', (560, 180), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,255,255), 2)

        # Cup - hình tròn
        cv2.circle(img, (200, 100), 40, (200, 150, 50), -1)
        cv2.putText(img, 'CUP', (185, 110), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,255,255), 2)

        self.image_path = '/kaggle/working/sample_image.png'
        cv2.imwrite(self.image_path, img)
        return img

    def extract_layers_simple(self, image_path=None):
        """
        Tách layers đơn giản - Giả định có sẵn 5 vật thể
        Output: Danh sách layers với depth
        """
        print("\n" + "="*60)
        print("BẮT ĐẦU TÁCH LAYERS")
        print("="*60)

        # Tải hoặc tạo ảnh
        if image_path and os.path.exists(image_path):
            image = cv2.imread(image_path)
            print(f"📸 Đã tải ảnh: {image_path}")
        else:
            image = self.create_sample_image()
            print("📸 Đã tạo ảnh mẫu")

        h, w = image.shape[:2]

        # Định nghĩa các layers (giả định)
        # Format: [tên, bbox, depth, màu]
        layers_def = [
            {
                "name": "background",
                "bbox": [0, 0, w, h],  # Toàn bộ ảnh
                "depth": 0.10,  # Xa nhất
                "color": (200, 220, 240)
            },
            {
                "name": "cup",
                "bbox": [160, 60, 80, 80],  # x, y, w, h
                "depth": 0.91,  # Gần
                "color": (200, 150, 50)
            },
            {
                "name": "book",
                "bbox": [100, 150, 300, 250],
                "depth": 0.85,  # Khá gần
                "color": (180, 120, 80)
            },
            {
                "name": "pen",
                "bbox": [450, 200, 50, 150],
                "depth": 0.88,  # Gần
                "color": (60, 60, 180)
            },
            {
                "name": "notebook",
                "bbox": [550, 100, 150, 150],
                "depth": 0.75,  # Trung bình
                "color": (80, 160, 80)
            }
        ]

        # Tạo và lưu từng layer
        layers_info = []

        print("\n📁 TẠO CÁC LAYERS:")
        print("-" * 50)

        for i, layer_def in enumerate(layers_def):
            # Tạo mask từ bbox
            mask = np.zeros((h, w), dtype=np.uint8)
            x, y, w_box, h_box = layer_def["bbox"]
            mask[y:y+h_box, x:x+w_box] = 1

            # Tạo layer image
            if layer_def["name"] == "background":
                # Background: giữ nguyên ảnh
                layer_img = image.copy()
            else:
                # Vật thể: nền trong suốt
                layer_img = cv2.cvtColor(image, cv2.COLOR_BGR2RGBA)
                layer_img[:, :, 3] = np.where(mask, 255, 0)

                # Chỉ giữ pixels của vật thể
                for c in range(3):
                    layer_img[:, :, c] = layer_img[:, :, c] * mask

            # Lưu file
            filename = f"{i:02d}_{layer_def['name']}.png"
            filepath = f"/kaggle/working/output/layers/{filename}"

            if layer_def["name"] == "background":
                cv2.imwrite(filepath, layer_img)
            else:
                cv2.imwrite(filepath, layer_img)

            # Thông tin layer
            layer_info = {
                "id": i,
                "name": layer_def["name"],
                "depth": layer_def["depth"],
                "file": filename,
                "bbox": layer_def["bbox"],
                "pixels": int(np.sum(mask))
            }

            layers_info.append(layer_info)

            # In thông tin
            print(f"  ✅ Layer {i}: {layer_def['name']:12} (depth={layer_def['depth']:.2f})")
            print(f"       File: {filename}")
            print(f"       Bbox: {layer_def['bbox']}")
            print(f"       Pixels: {layer_info['pixels']:,}")
            print()

        # Sắp xếp theo depth (từ xa đến gần)
        sorted_by_depth = sorted(layers_info, key=lambda x: x['depth'])

        print("\n📊 THỨ TỰ DEPTH (từ xa đến gần):")
        print("-" * 50)
        for i, layer in enumerate(sorted_by_depth):
            print(f"  {i}. {layer['name']:12} - depth: {layer['depth']:.2f}")

        # Lưu metadata
        self.save_metadata(layers_info, image_path or "sample_image.png")

        # Hiển thị kết quả
        self.visualize_layers(image, layers_info)

        return layers_info

    def save_metadata(self, layers_info, image_path):
        """Lưu metadata"""
        metadata = {
            "timestamp": datetime.now().isoformat(),
            "source_image": image_path,
            "total_layers": len(layers_info),
            "layers": layers_info
        }

        with open('/kaggle/working/output/metadata.json', 'w') as f:
            json.dump(metadata, f, indent=2)

        print(f"\n💾 Đã lưu metadata: /kaggle/working/output/metadata.json")

    def visualize_layers(self, original_image, layers_info):
        """Hiển thị visualization đơn giản"""
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(2, 3, figsize=(15, 10))

        # 1. Ảnh gốc
        axes[0,0].imshow(cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB))
        axes[0,0].set_title("🎨 ẢNH GỐC", fontweight='bold', fontsize=12)
        axes[0,0].axis('off')

        # 2. Depth visualization
        depth_map = np.zeros(original_image.shape[:2], dtype=np.float32)
        for layer in layers_info:
            if layer['name'] != 'background':
                x, y, w_box, h_box = layer['bbox']
                depth_map[y:y+h_box, x:x+w_box] = layer['depth']

        im = axes[0,1].imshow(depth_map, cmap='viridis')
        axes[0,1].set_title("🗺️ DEPTH MAP", fontweight='bold', fontsize=12)
        axes[0,1].axis('off')
        plt.colorbar(im, ax=axes[0,1], fraction=0.046, pad=0.04)

        # 3. Danh sách layers
        axes[0,2].axis('off')
        info_text = "📋 DANH SÁCH LAYERS:\n\n"
        for layer in sorted(layers_info, key=lambda x: x['depth']):
            info_text += f"• {layer['name']:12} (depth={layer['depth']:.2f})\n"
            info_text += f"  File: {layer['file']}\n"
            info_text += f"  Pixels: {layer['pixels']:,}\n\n"

        axes[0,2].text(0.1, 0.95, info_text, transform=axes[0,2].transAxes,
                      fontsize=9, verticalalignment='top',
                      bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

        # 4-6. Hiển thị 3 layers đầu tiên
        for idx, layer_idx in enumerate([1, 2, 3]):
            if layer_idx < len(layers_info):
                layer = layers_info[layer_idx]
                filepath = f"/kaggle/working/output/layers/{layer['file']}"

                if os.path.exists(filepath):
                    layer_img = cv2.imread(filepath, cv2.IMREAD_UNCHANGED)

                    if layer_img is not None:
                        if len(layer_img.shape) == 3 and layer_img.shape[2] == 4:
                            axes[1, idx].imshow(cv2.cvtColor(layer_img, cv2.COLOR_BGRA2RGBA))
                        else:
                            axes[1, idx].imshow(cv2.cvtColor(layer_img, cv2.COLOR_BGR2RGB))

                        axes[1, idx].set_title(f"📄 {layer['name'].upper()}\ndepth={layer['depth']:.2f}",
                                              fontweight='bold', fontsize=11)
                        axes[1, idx].axis('off')

        plt.suptitle("KẾT QUẢ TÁCH LAYERS - SIMPLE EXTRACTOR",
                    fontsize=16, fontweight='bold', y=1.02)
        plt.tight_layout()
        plt.savefig('/kaggle/working/output/layers_summary.png', dpi=150, bbox_inches='tight')
        plt.show()

        print(f"\n📈 Đã tạo visualization: /kaggle/working/output/layers_summary.png")

from google.colab import drive
drive.mount('/content/drive')

# CELL 3: CHẠY EXTRACTOR
# Khởi tạo
extractor = SimpleLayerExtractor()

# Chạy pipeline
print("🚀 BẮT ĐẦU QUÁ TRÌNH TÁCH LAYERS")
print("="*60)

layers = extractor.extract_layers_simple()

print("\n" + "="*60)
print("✅ HOÀN THÀNH!")
print("="*60)
print("\n📁 OUTPUT TRONG /kaggle/working/output/:")
print("-" * 50)

import glob
output_files = glob.glob('/kaggle/working/output/**', recursive=True)
for file in sorted(output_files):
    if os.path.isfile(file):
        size_kb = os.path.getsize(file) / 1024
        print(f"  • {os.path.basename(file):30} ({size_kb:.1f} KB)")

# CELL 4: HIỂN THỊ KẾT QUẢ CHI TIẾT
print("\n🎯 KẾT QUẢ CHI TIẾT:")
print("="*60)

# Đọc metadata
import json
with open('/kaggle/working/output/metadata.json', 'r') as f:
    metadata = json.load(f)

print(f"\n📊 TỔNG SỐ LAYERS: {metadata['total_layers']}")
print(f"📸 ẢNH NGUỒN: {metadata['source_image']}")
print(f"⏰ THỜI GIAN: {metadata['timestamp']}")

print("\n📋 DANH SÁCH LAYERS:")
print("-" * 50)

# Sắp xếp theo depth
sorted_layers = sorted(metadata['layers'], key=lambda x: x['depth'])

for i, layer in enumerate(sorted_layers):
    depth_bar = "█" * int(layer['depth'] * 10)
    print(f"\n{i}. {layer['name'].upper():12}")
    print(f"   📍 Depth: {layer['depth']:.2f} {depth_bar}")
    print(f"   📄 File: {layer['file']}")
    print(f"   🎯 Pixels: {layer['pixels']:,}")
    print(f"   📐 Bbox: {layer['bbox']}")

print("\n" + "="*60)
print("📦 ĐỂ TẢI VỀ: Nén thư mục /kaggle/working/output/")
print("="*60)

# CELL 5: TẠO ẢNH TỔNG HỢP VÀ NÉN KẾT QUẢ
# Tạo ảnh tổng hợp tất cả layers
import matplotlib.pyplot as plt
from PIL import Image

print("🖼️ Tạo ảnh tổng hợp tất cả layers...")

# Đọc tất cả layers
layer_files = sorted([f for f in os.listdir('/kaggle/working/output/layers')
                     if f.endswith('.png')])

fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes = axes.flatten()

for i, filename in enumerate(layer_files[:6]):  # Tối đa 6 layers
    filepath = f"/kaggle/working/output/layers/{filename}"
    img = cv2.imread(filepath, cv2.IMREAD_UNCHANGED)

    if img is not None:
        if len(img.shape) == 3 and img.shape[2] == 4:
            axes[i].imshow(cv2.cvtColor(img, cv2.COLOR_BGRA2RGBA))
        else:
            axes[i].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

        # Lấy tên layer từ filename
        layer_name = filename.split('_')[1].replace('.png', '')
        axes[i].set_title(f"Layer: {layer_name}", fontweight='bold')
        axes[i].axis('off')
    else:
        axes[i].axis('off')

# Ẩn axes không dùng
for i in range(len(layer_files), len(axes)):
    axes[i].axis('off')

plt.suptitle("TẤT CẢ LAYERS ĐÃ TÁCH", fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig('/kaggle/working/output/all_layers_grid.png', dpi=150, bbox_inches='tight')
plt.show()

# Nén kết quả
print("\n📦 Đang nén kết quả...")
!cd /kaggle/working && zip -r output.zip output/

print("\n" + "="*60)
print("✅ HOÀN THÀNH TẤT CẢ!")
print("="*60)
print("\n📁 CÁC FILE ĐÃ TẠO:")
print("-" * 50)

for root, dirs, files in os.walk('/kaggle/working'):
    for file in files:
        if file.endswith(('.png', '.jpg', '.json', '.zip')):
            filepath = os.path.join(root, file)
            rel_path = os.path.relpath(filepath, '/kaggle/working')
            size_kb = os.path.getsize(filepath) / 1024
            print(f"  • {rel_path:40} ({size_kb:.1f} KB)")

print("\n📥 TẢI VỀ: Click phải vào 'output.zip' trong file browser → Download")